# Generated by Django 5.2.7 on 2025-11-01 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vtonrequest',
            name='cloths_on',
        ),
        migrations.RemoveField(
            model_name='vtonrequest',
            name='confidence_score',
        ),
        migrations.RemoveField(
            model_name='vtonrequest',
            name='instructions',
        ),
        migrations.RemoveField(
            model_name='vtonrequest',
            name='quality_score',
        ),
    ]
