# Generated by Django 5.2.7 on 2025-11-01 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_vtonrequest_cloths_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiusagelog',
            name='api_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='app.apikey'),
        ),
    ]
