# Generated by Django 5.2.7 on 2025-11-02 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_apiusagelog_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='api_key_generation_enabled',
            field=models.BooleanField(default=True, help_text='Whether user can generate new API keys'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='default_monthly_quota',
            field=models.IntegerField(default=500, help_text='Default monthly quota for new API keys'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='default_rate_limit_per_day',
            field=models.IntegerField(default=10000, help_text='Default per-day rate limit for new API keys'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='default_rate_limit_per_hour',
            field=models.IntegerField(default=1000, help_text='Default per-hour rate limit for new API keys'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='default_rate_limit_per_minute',
            field=models.IntegerField(default=100, help_text='Default per-minute rate limit for new API keys'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='max_api_keys',
            field=models.IntegerField(default=5, help_text='Maximum number of API keys user can create'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='user_monthly_quota',
            field=models.IntegerField(default=1000, help_text="Total monthly quota across all user's API keys"),
        ),
    ]
