# Generated by Django 5.2.7 on 2025-11-19 19:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_userdata_api_key_generation_enabled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='When the user was approved', null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Admin who approved the user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userdata',
            name='is_api_approved',
            field=models.BooleanField(default=False, help_text='Whether user is approved to create API keys'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='api_key_generation_enabled',
            field=models.BooleanField(default=False, help_text='Whether user can generate new API keys - set by admin when approving request'),
        ),
        migrations.CreateModel(
            name='APIKeyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('requested_key_name', models.CharField(help_text='Name for the requested API key', max_length=100)),
                ('reason', models.TextField(help_text="User's reason for requesting an API key")),
                ('intended_use', models.TextField(blank=True, help_text='Description of how the API key will be used')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When the request was reviewed', null=True)),
                ('payment_date', models.DateField(blank=True, help_text='Date when payment was received', null=True)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Payment amount received', max_digits=10, null=True)),
                ('payment_proof', models.FileField(blank=True, help_text='Payment proof/receipt attachment', null=True, upload_to='api_requests/payment_proofs/')),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes from admin/staff')),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection (if rejected)')),
                ('requested_rate_limit_per_minute', models.IntegerField(blank=True, help_text='Requested per-minute rate limit', null=True)),
                ('requested_rate_limit_per_hour', models.IntegerField(blank=True, help_text='Requested per-hour rate limit', null=True)),
                ('requested_rate_limit_per_day', models.IntegerField(blank=True, help_text='Requested per-day rate limit', null=True)),
                ('requested_monthly_quota', models.IntegerField(blank=True, help_text='Requested monthly quota', null=True)),
                ('approved_rate_limit_per_minute', models.IntegerField(blank=True, help_text='Approved per-minute rate limit', null=True)),
                ('approved_rate_limit_per_hour', models.IntegerField(blank=True, help_text='Approved per-hour rate limit', null=True)),
                ('approved_rate_limit_per_day', models.IntegerField(blank=True, help_text='Approved per-day rate limit', null=True)),
                ('approved_monthly_quota', models.IntegerField(blank=True, help_text='Approved monthly quota', null=True)),
                ('approved_expires_in_days', models.IntegerField(blank=True, help_text='Number of days until key expires (null = never)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional request metadata')),
                ('generated_api_key', models.ForeignKey(blank=True, help_text='The API key created from this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_request', to='app.apikey')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin/staff who reviewed the request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_api_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_key_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Key Request',
                'verbose_name_plural': 'API Key Requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='app_apikeyr_user_id_10f2f6_idx'), models.Index(fields=['status', '-created_at'], name='app_apikeyr_status_427707_idx'), models.Index(fields=['reviewed_by', '-reviewed_at'], name='app_apikeyr_reviewe_b7cd92_idx')],
            },
        ),
    ]
