# Generated by Django 5.2.7 on 2025-11-02 14:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VTONRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('person_image', models.FileField(max_length=512, upload_to='uploads/')),
                ('clothing_image', models.FileField(max_length=512, upload_to='uploads/')),
                ('person_image_original_name', models.CharField(max_length=256)),
                ('clothing_image_original_name', models.CharField(max_length=256)),
                ('result_image', models.FileField(blank=True, max_length=512, null=True, upload_to='output/')),
                ('instructions', models.TextField(blank=True, default='')),
                ('cloths_on', models.BooleanField(default=False, help_text='DEPRECATED: This field is no longer used. Vertex AI automatically handles both scenarios.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='client_api__created_2c3032_idx'), models.Index(fields=['status'], name='client_api__status_df357e_idx')],
            },
        ),
    ]
