# Generated by Django 5.2.7 on 2025-11-08 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_userdata_api_key_generation_enabled_and_more'),
        ('client_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vtonrequest',
            name='api_key',
            field=models.ForeignKey(blank=True, help_text='API key used for this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_api_vton_requests', to='app.apikey'),
        ),
    ]
